# include: package:very_good_analysis/analysis_options.yaml
include: package:solid_lints/analysis_options.yaml


linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    use_setters_to_change_properties: false
    one_member_abstracts: false
    always_use_package_imports: false
    prefer_relative_imports: true

analyzer:
  plugins:
    - custom_lint
  exclude:
    - member_ordering: false
    - 'lib/l10n/*.dart'