name: samba_public_app
description: 'Samba Public App'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.19.5

dependencies:
  country_picker: ^2.0.25
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.2
  dio: ^5.4.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dynamic_height_grid_view: ^0.0.4
  easy_image_viewer: ^1.4.1
  extended_image: ^8.2.0
  fast_immutable_collections: ^10.2.2
  fetch_client: ^1.0.2
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.1
  hive_cache_manager: ^0.0.1
  intl: ^0.18.1
  logging: ^1.2.0
  native_dio_adapter: ^1.3.0
  path_provider: ^2.1.3
  pull_down_button: ^0.9.3
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2
  sliver_tools: ^0.2.12
  super_sliver_list: ^0.4.1
  transparent_image: ^2.0.1
  wolt_modal_sheet: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  dart_mappable_builder: ^4.2.3
  flutter_test:
    sdk: flutter
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    # Add assets from the images directory to the application.
    - assets/images/
