name: batucadapp
description: 'Samba Public App'

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: 3.22.0-0.3.pre

dependencies:
  const_date_time: ^1.1.0
  cupertino_icons: ^1.0.6
  dart_mappable: ^4.2.2
  dio: ^5.4.3
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dynamic_height_grid_view: ^0.0.4
  extended_image: ^8.2.0
  fast_immutable_collections: ^10.2.2
  fetch_client: ^1.1.1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.0.2
  intl: ^0.19.0
  logging: ^1.2.0
  native_dio_adapter: ^1.3.0
  path_provider: ^2.1.3
  pull_down_button: ^0.9.3
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.2.2
  sheet: ^1.0.0
  skeletonizer: ^1.1.2+1
  sliver_tools: ^0.2.12
  super_sliver_list: ^0.4.1
  transparent_image: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.11
  dart_mappable_builder: ^4.2.3
  dependency_validator: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  icons_launcher: ^2.1.7
  mocktail: ^1.0.3
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  solid_lints: ^0.1.2
  very_good_analysis: ^5.1.0
  

flutter:
  uses-material-design: true
  generate: true
  # Flutter engine issue, always download roboto on
  # web in the loadAssetFonts function https://github.com/flutter/engine/blob/main/lib/web_ui/lib/src/engine/canvaskit/fonts.dart
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  
  assets:
    # Add assets from the images directory to the application.
    - assets/
    - dotenv

icons_launcher:
  image_path: 'assets/ic_logo_border.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/ic_logo_border.png'
      adaptive_background_image: 'assets/ic_background.png'
      adaptive_foreground_image: 'assets/ic_foreground.png'
    ios:
      enable: true
      image_path: 'assets/ic_logo.png'
    web:
      enable: true
      image_path: 'assets/ic_logo_border.png'
      favicon_path: 'assets/ic_logo_round.png'

flutter_native_splash:
  color: "#100065"
  branding: assets/ic_foreground.png

  android_12:

  web: false