name: Run Tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
            channel: beta
            cache: true
            
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_URL: ${{ secrets.API_URL }}
        
      - run: flutter test