name: Github-Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: beta
          cache: true
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_API_URL: ${{ secrets.API_URL }}

      - name: Run Tests
        run: flutter test
        
      - name: Install dependencies
        run: flutter pub get

      # 404.html and flutter_bootstrap.js are mannually added to the web folder to
      # fix the 404 error on GH Pages and fix PWA Padding issue
      - name: Build web
        run: flutter build web --wasm --base-href /batucadapp/ --no-web-resources-cdn

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git --work-tree build/web add --all
          git commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages --force
        shell: bash
